source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.4"

gem "bootsnap", require: false
gem "impulse_view_components", path: "../"
gem "jsbundling-rails"
gem "lookbook", "~> 2.0", ">= 2.0.5"
gem "puma", "~> 5.6"
gem "rails", "6.1.7"
gem "sprockets"
gem "sprockets-rails"
gem "sqlite3", "~> 1.4"
gem "standard", "~> 1.3"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "byebug"
  gem "debug", platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem "web-console"
end
